Tasks are now executed and tracked line by line Added vars.yml to allow dynamic variable definitions

diff --git a/lib/each_deploy b/lib/each_deploy
--- a/lib/each_deploy
+++ b/lib/each_deploy
@@ -9,8 +9,7 @@
 #	${hosts[@]}
 #	${tasks[@]}
 
-# Abort on error
-set -e;
+# Abort on error is deffered to trap ERR caught
 
 track "screen" "$green$counter) Project $id$std"
 
@@ -18,7 +17,7 @@ copy_path=$copy_dir"/"$release_name"/"${!branch}
 
 if [ ! -f "$copy_path/$release_name.tgz" ] ; 
 then
-	exec_wrap "$id:clone" $method $repository $copy_path"/"$release_name
+	exec_wrap "$id:clone" $method "-b ${!branch} --single-branch" $repository $copy_path"/"$release_name
 	exec_wrap "$id:clone:clean" rm -rf $copy_path"/"$release_name"/".git
 	exec_wrap "$id:compress" tar -zcf $copy_path/$release_name.tgz -C $copy_path"/" $release_name
 fi
@@ -47,18 +46,18 @@ do
 		if [[ $task == "tasks-common"* ]] ; 
 			then 
 			 replace_vars $abs_path"/"$task
-			 exec_wrap "$id:task:$task" ssh ${!user}@${!host} $commmand
+			 exec_wrap "$id:remote:task:$task" ssh ${!user}@${!host} "$commmand"
 			else
-			 replace_vars $abs_path"/"$task
-			 exec_wrap "$id:task:$task" ssh ${!user}@${!host} $commmand
+			 replace_vars $task
+			 exec_wrap "$id:remote:task:$task" ssh ${!user}@${!host} "$commmand"
 		fi
 	done
 
 	replace_vars $abs_path"/tasks-native/current-new-release"
-	exec_wrap "$id:task:publish" ssh ${!user}@${!host} $commmand
+	exec_bloc_wrap "$id:remote:task:publish" ssh ${!user}@${!host} "$commmand"
 
 	# keep_releases : delete too old releases
 	replace_vars $abs_path"/tasks-native/keep-releases"
-	exec_wrap "$id:task:keep_releases" ssh ${!user}@${!host} $commmand
+	exec_bloc_wrap "$id:remote:task:keep_releases" ssh ${!user}@${!host} "$commmand"
 done
 
diff --git a/lib/wrappers b/lib/wrappers
--- a/lib/wrappers
+++ b/lib/wrappers
@@ -33,28 +33,56 @@ function track {
 }
 
 function exec_wrap {
-	track "info"  "$@"
 
-	# args line without first argument, first argument indicates the vhost id deploy running
-	returned=$("${@:2}" 2>&1)
-	# old method when command was launched this way $("${@:2}" 2>&1) | tee -a $log_file
-	#status=${PIPESTATUS[0]}
-	status=$?
+ 	if [ "$2" == "ssh" ];
+        then
+         ssh_prefix="$2 $3 ";
+         comm="${@:4}"
+     else
+        ssh_prefix="";
+         comm="${@:2}"
+    fi
+    
+    IFSBACK=$IFS
+    IFS=$'\n'
+        for line in $comm
+        do
+            track "info" "$1" $ssh_prefix$line
+            IFS=$IFSBACK
+            execute $ssh_prefix$line
+            IFS=$'\n'
+        done
+    IFS=$IFSBACK
 
-	if [ "$returned" != "" ] ; then
-		track "warning" "return: $returned"
-		if [[ "$returned" == "bash: "* ]] || [[ "$returned" == "sh: "* ]] ; then
-			track "error" "Deploy failed on $@ because of remote interpreter syntax error";
-			exit 1
-		fi
+}
 
-	fi
+# use only for launch native tasks : allow to run a whole task file in one command (easier to read )
+function exec_bloc_wrap {
+	track "info"  "$1" "${@:2}"
+ 	execute "${@:2}";
+}
 
-	if [ "$status" -ne 0 ] ; 
-	then
-		track "error" "Deploy failed on $@ with status $status";
-		exit $status
-	fi 
+function execute {
+    # args line without first argument, first argument indicates the vhost id deploy running
+    returned=$("$@" 2>&1)
+    # old method when command was launched this way $("${@:2}" 2>&1) | tee -a $log_file
+    #status=${PIPESTATUS[0]}
+    status=$?
+
+    if [ "$returned" != "" ] ; then
+        track "warning" "return: $returned"
+        if [[ "$returned" == "bash: "* ]] || [[ "$returned" == "sh: "* ]] ; then
+            track "error" "Deploy failed because of bash error.";
+            exit 1
+        fi
+
+    fi
+
+    if [ "$status" -ne 0 ] ; 
+    then
+        track "error" "Deploy failed with status $status.";
+        exit $status
+    fi 
 
 }
 
